FROM centos:6

# Install Ansible
RUN yum -y update; yum clean all;
RUN yum -y install epel-release
RUN yum -y install git gcc sudo libffi-devel openssl-devel
RUN yum clean all

RUN git clone https://github.com/tagomoris/xbuild.git && \
    xbuild/python-install 2.7.9 /opt/python-2.7 && \
    /opt/python-2.7/bin/pip install ansible


# Disable requiretty
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# Install Ansible inventory file
RUN mkdir - p /etc/ansible
RUN echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

CMD ["/usr/sbin/init"]
